name: set output

on:
  push:
    branches:
      - main

jobs:
   job1:
    runs-on: ubuntu-latest
    outputs:
      job1_name: ${{ steps.set-output.outputs.name }}
    
    steps:
      - name: greetings
        id: set-ouput
        run: |
          echo "name=vamsi" >> $GITHUB_OUTPUT

      - name: access output
        run: |
          echo "the value of output name is ${{ steps.set-output.outputs.name }}"
jobs2:
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      - name: access output2
        run: |
          echo "the value of output job1 is ${{ needs.jobs1.outputs.job1_name }}"
        
