name: Set Output

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1_name: ${{ steps.set-output.outputs.name }}
    
    steps:
      - name: Greetings
        id: set-output
        run: |
          echo "name=vamsi" >> $GITHUB_OUTPUT

      - name: Access output
        run: |
          echo "The value of output name is ${{ steps.set-output.outputs.name }}"

  jobs2:
    runs-on: ubuntu-latest
    needs: job1
    
    steps:
      - name: Access output from Job 1
        run: |
          echo "The value of output job1 is ${{ needs.job1.outputs.job1_name }}"
