name: manual world

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      age:
        description: 'age'
        type: number
        required: true

jobs:
  manual:
    runs-on: ubuntu-latest
    
    steps:
      - name: greetings
        run: echo "${{ github.event.inputs.name }}"
      - name: age
        run: echo "${{ github.event.inputs.age }}"
