name: manual world

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      name:
        description: 'age'
        type: number
        required: true 
        
  
jobs:
  manual:
    runs-on: ubuntu-latest
    
    steps:
      - name: greetings
        run: echo "${{ input.name }}"
    
    steps:
      - name: age
        run: echo "${{ input.name }}"

        
