name: manual world

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      age:
        description: 'Age'
        type: number
        required: true
      gender:
        description: 'Gender'
        type: choice
        options:
          - Male
          - Female
      married:
        description: 'Is married'
        type: boolean
      Env:
        description: 'Namespace'
        required: true
        default: 'hhhjf'
        type: string
      Service:
        description: 'Service to deploy'
        required: true
        default: 'hhh'
        type: string  

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello, ${{ github.event.inputs.name }}!"
      - name: Age
        run: echo "Your age is ${{ github.event.inputs.age }}."
      - name: Gender
        run: echo "Your gender is ${{ github.event.inputs.gender }}."
      - name: Marital Status
        run: |
          if [[ "${{ github.event.inputs.married }}" == "true" ]]; then
            echo "You are married."
          else
            echo "You are not married."
          fi
      - name: Environment
        run: |
          if [[ -z "${{ github.event.inputs.Env }}" ]]; then
            echo "Error: Namespace input is missing or invalid!"
            exit 1
          else
            echo "Namespace: ${{ github.event.inputs.Env }}"
          fi
      - name: Service
        run: |
          if [[ -z "${{ github.event.inputs.Service }}" ]]; then
            echo "Error: Service input is missing or invalid!"
            exit 1
          else
            echo "Service to deploy: ${{ github.event.inputs.Service }}"
          fi
