name: manual world

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
        
  
jobs:
  manual:
    runs-on: ubuntu-latest
    
    steps:
      - name: greetings
        run: echo "${{ input.name }}"

        
