name: manual world

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        type: string
        default: 'test'
      age:
        description: 'age'
        type: number
        required: true
      gender:
        description: 'gender'
        type: choice
        options:
          - Male
          - Female
      married:
        description: 'Is married'
        type: boolean

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "${{ github.event.inputs.name }}"
      - name: Age
        run: echo "${{ github.event.inputs.age }}"
      - name: Gender
        run: echo "${{ github.event.inputs.gender }}"
      - name: Married
        run: echo "${{ github.event.inputs.married }}"
