name: set output

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
      - name: greetings
        id: set-ouput
        shell: bash
        run: |
          echo "name=vamsi" >> $GITHUB_OUTPUT
          echo "age=28" >> $GITHUB_OUTPUT

      - name: hello
        id: set-ouput2
        shell: bash
        run: |
          echo "salary=2000" >> $GITHUB_OUTPUT

      - name: access output
        run: |
          echo "the value of output name is ${{ steps.set-output.outputs.name }}"
          echo "the value of output age is ${{ steps.set-output.outputs.age }}"
      - name: access output2
        run: |
          echo "the value of output salary is ${{ steps.set-output2.outputs.salary }}"
        
